### PR TITLE
optipng-ed files and updated Polish translation

### PR DESCRIPTION
**Pull request by mkljczk**
BTW, what happened to duckduckgo/android repo?

### CODE REVIEW

**Comment by fgei** [comment]
@m4sk1n you can find it here: https://github.com/duckduckgo/android-search-and-stories

**Comment by mkljczk** [comment]
@fgei and what with my pull request here?

**Comment by fgei** [comment]
@m4sk1n I'll review and merge the PR on https://github.com/duckduckgo/android-search-and-stories and close this PR

**Comment by mkljczk** [comment]
I'm still waiting

**Pull request closed without merging**
